# Start from base image
# Search in Docker hub
# alpine - small linux distribution
FROM node:alpine
# Copy app files
# all files from . to /app
COPY . /app
# execute command
# WORKDIR /app
CMD node /app/app.js
